###
# POST SIGN_UP
# This call will create a new user account
POST http://superBrackets.herokuapp.com/signup
Content-Type: application/json

{
    "email": "testing@test.com",
    "password": "password",
    "confirmPassword": "password"
}


###
# POST LOGIN
# This is the endpoint to login. It will return an
# access token that can be used to access protected 
#endpoints
POST http://superBrackets.herokuapp.com/login 
Content-Type: application/json

{
    "email": "testing@test.com",
    "password": "password"
}


###
# POST Token
# This call is how the user gets a new access token after
# one expires. They must provide their refresh token
# Access tokens are only valid for 1min for demonstrative purposes. Typically
# the access token would expire within seconds of of the creation which requires
# the user to frequently refresh their access token.
POST http://superBrackets.herokuapp.com/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vyc0JyYWNrZXRzIjp7ImJyYWNrZXQiOltdfSwiX2lkIjoiNjFiMjgwM2VkNWYzNDFkODVhOTFlMDZmIiwiZW1haWwiOiJ0ZXN0aW5nQHRlc3QuY29tIiwicGFzc3dvcmQiOiIkMmIkMTIkdVNvcjRBMHM0RXNpVjI4bjZHTDlidWpiZkJnU3o4OS9CZkE0aFZTaDFVNUpWd3FxbTE3SEciLCJfX3YiOjAsImlhdCI6MTYzOTExODAzNn0.DJsm3mKUGTFaU9pOpPAmbN1gsN5hJUR0JwcT024jzcM"
}


###
# GET BRACKETS-LIST
# This call returns all the brackets
GET http://superBrackets.herokuapp.com/brackets-list


###
# GET BRACKET
# This call returns a single bracket
GET http://superBrackets.herokuapp.com/bracket/:bracketId


###
# GET ADVANCE_PARTICIPANT
# This request will advance the first person in the previous bracket
GET http://superBrackets.herokuapp.com/advance-participant/:bracketId/:participantId
Authorization: Bearer <ACCESS_TOKEN>


###
# POST EDIT_BRACKET
# In this edit, we are reseting the advance-participant that took place
POST http://superBrackets.herokuapp.com/edit-bracket/:bracketId
Content-Type: application/json
Authorization: Bearer <ACCESS_TOKEN>

{

        "title": "test bracket",
        "description": "This brakcet is a test!",
        "participants": [
            {
            "name": "person1",
            "round": 1,
            "_id": "61a87596f161526f1bbb80d5"
            },
            {
            "name": "person2",
            "round": 1,
            "_id": "61a87596f161526f1bbb80d6"
            },
            {
            "name": "person3",
            "round": 1,
            "_id": "61a87596f161526f1bbb80d7"
            },
            {
            "name": "person4",
            "round": 1,
            "_id": "61a87596f161526f1bbb80d8"
            }
        ]
}


###
# POST ADD_BRACKET
# This call will create a new bracket in the database
# The user must be authenticated to perform this action
POST http://superBrackets.herokuapp.com/add-bracket
Content-Type: application/json
Authorization: Bearer <ACCESS_TOKEN>

{
    "title": "Just another Test 2",
    "description": "this is one of many test brackets",
    "participants": ["Braden", "Brenton", "Nate", "Samuel"]
}


###
# DELETE DELETE_BRACKET
# This call will create a new bracket in the database
# The user must be authenticated to perform this action
DELETE http://superBrackets.herokuapp.com/delete/:bracketId
Authorization: Bearer <ACCESS_TOKEN>


###
# DELETE LOGOUT
# This request will logout the user by destroying their refresh token.
# They will have to login to get another.
DELETE http://superBrackets.herokuapp.com/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vyc0JyYWNrZXRzIjp7ImJyYWNrZXQiOltdfSwiX2lkIjoiNjFiMjgwM2VkNWYzNDFkODVhOTFlMDZmIiwiZW1haWwiOiJ0ZXN0aW5nQHRlc3QuY29tIiwicGFzc3dvcmQiOiIkMmIkMTIkdVNvcjRBMHM0RXNpVjI4bjZHTDlidWpiZkJnU3o4OS9CZkE0aFZTaDFVNUpWd3FxbTE3SEciLCJfX3YiOjAsImlhdCI6MTYzOTE4MzgzN30.SH3u_RbVB6yk2tVGErCRFB0mEbyRxmnb_sO5RsBP9iU"
}