###
# POST SIGN_UP
# This call will create a new user account
POST http://127.0.0.1:3000/signup
Content-Type: application/json

{
    "email": "testing@test.com",
    "password": "password",
    "confirmPassword": "password"
}


###
# POST LOGIN
# This is the endpoint to login. It will return an
# access token that can be used to access protected 
#endpoints
POST http://127.0.0.1:3000/login 
Content-Type: application/json
{
    "email": "testing@test.com",
    "password": "password"
}


###
# POST ADD BRACKET
POST http://127.0.0.1:3000/add-bracket/Sample bracket/This is a test/Player 1@Player 2@Player 3@Player 4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vyc0JyYWNrZXRzIjp7ImJyYWNrZXQiOltdfSwiX2lkIjoiNjFiMTdmMzQzNjlhY2ZiMGFkNjIwZTNiIiwiZW1haWwiOiJuYXRlZHVuY2FuMEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRuWjl0Q3FmWmZJWkF4TmNWVnVDWUVlSU9JZEpneWtqMlAyTWxxWTh6VlN0VGtpZWRFNFZ5MiIsIl9fdiI6MCwiaWF0IjoxNjM5MDIzMjUwfQ.LBuhMhHJ95NTtCX1ojeU7zn7kHK9Oz6_OjjyqzOcrTE

@ourBracketID = ""
@ourParticipantID = ""

###
# GET BRACKET
# This call returns the bracket we made
GET http://127.0.0.1:3000/bracket/{{ourBracketID}}

###
# GET ADVANCE_PARTICIPANT
# This request will advance the first person in the previous bracket
GET http://127.0.0.1:3000/advance-participant/{{ourBracketID}}/{{ourParticipantID}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vyc0JyYWNrZXRzIjp7ImJyYWNrZXQiOltdfSwiX2lkIjoiNjFiMTdmMzQzNjlhY2ZiMGFkNjIwZTNiIiwiZW1haWwiOiJuYXRlZHVuY2FuMEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRuWjl0Q3FmWmZJWkF4TmNWVnVDWUVlSU9JZEpneWtqMlAyTWxxWTh6VlN0VGtpZWRFNFZ5MiIsIl9fdiI6MCwiaWF0IjoxNjM5MDIzMjUwfQ.LBuhMhHJ95NTtCX1ojeU7zn7kHK9Oz6_OjjyqzOcrTE

###
# GET BRACKET
# Testing that the participant was advanced
GET http://127.0.0.1:3000/bracket/{{ourBracketID}}

###
# GET DELETE BRACKET
# deleting the bracket we made
http://127.0.0.1:3000/delete/{{ourBracketID}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vyc0JyYWNrZXRzIjp7ImJyYWNrZXQiOltdfSwiX2lkIjoiNjFiMTdmMzQzNjlhY2ZiMGFkNjIwZTNiIiwiZW1haWwiOiJuYXRlZHVuY2FuMEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRuWjl0Q3FmWmZJWkF4TmNWVnVDWUVlSU9JZEpneWtqMlAyTWxxWTh6VlN0VGtpZWRFNFZ5MiIsIl9fdiI6MCwiaWF0IjoxNjM5MDIzMjUwfQ.LBuhMhHJ95NTtCX1ojeU7zn7kHK9Oz6_OjjyqzOcrTE

###
# Showing the bracket was deleted
GET http://127.0.0.1:3000/bracket/{{ourBracketID}}